import { Container, Heading } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'

import { TodoList } from '@/components/TodoList'

const Page: NextPage = () => {
  return (
    <Container maxW="container.lg">
      <Head>
        <title>Recoil Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading as="h1" mt="4">
        Recoil Todo App
      </Heading>
      <TodoList />
    </Container>
  )
}

export default Page
