import { Container, Heading } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'

const Page: NextPage = () => {
  return (
    <Container maxW="container.lg">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading as="h1" size="xl" mt="3">
        ログイン
      </Heading>
    </Container>
  )
}

export default Page
